#!/bin/sh
# worklog:post-pull-hook:v1
# Wrapper that delegates to central Worklog post-pull script (committed hooks).
exec "/home/rogardle/projects/classic-arcade/gpt120_test_1/.githooks/worklog-post-pull" "$@"
